services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - ${MYSQL_LOCAL_HOME}:/var/lib/mysql
    networks:
      - wordpress

  wordpress:
    depends_on:
      - database
    image: wordpress:php8.3-fpm-alpine
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_TABLE_PREFIX: '${WORDPRESS_TABLE_PREFIX}'
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${WORDPRESS_UPLOADS_CONFIG}:/usr/local/etc/php/conf.d/uploads.ini
    networks:
      - wordpress

  nginx:
    depends_on:
      - wordpress
    image: nginx:latest
    container_name: wp-nginx
    env_file: .env
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ${WORDPRESS_LOCAL_HOME}:/var/www/html
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_LOGS}:/var/log/nginx
    networks:
      - wordpress

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8081:80
    env_file: .env
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - wordpress

volumes:
  db-data:

networks:
  wordpress:
    driver: bridge
